-- -- Git
-- vim.api.nvim_set_hl(0, "GitSignsAdd", { fg = colors.teal, bg = colors.none })
--
-- -- NeoTree
-- vim.api.nvim_set_hl(0, "NeoTreeTitleBar", { fg = colors.bg, bg = colors.purple })
--
-- -- Telescope
-- vim.api.nvim_set_hl(0, "TelescopeBorder", { bg = colors.none, fg = colors.blue7 })
-- vim.api.nvim_set_hl(0, "TelescopeNormal", { bg = colors.bg, fg = colors.fg })
-- vim.api.nvim_set_hl(0, "TelescopePromptTitle", { bg = colors.none, fg = colors.purple })
-- vim.api.nvim_set_hl(0, "TelescopePreviewTitle", { bg = colors.none, fg = colors.purple })
-- vim.api.nvim_set_hl(0, "TelescopeResultsTitle", { bg = colors.none, fg = colors.purple })
-- vim.api.nvim_set_hl(0, "TelescopePromptPrefix", { bg = colors.none, fg = colors.purple })
-- vim.api.nvim_set_hl(0, "TelescopeSelection", { bg = colors.terminal_black, fg = "#FFFFFF" })
-- vim.api.nvim_set_hl(0, "TelescopeMatching", { bg = colors.none, fg = colors.magenta2 })
-- vim.api.nvim_set_hl(0, "TelescopeSelectionCaret", { bg = colors.terminal_black, fg = colors.comment })
--
-- -- Cmp
-- vim.api.nvim_set_hl(0, "PmenuSel", { bg = colors.terminal_black, fg = "#FFFFFF" })
-- vim.api.nvim_set_hl(0, "Pmenu", { fg = colors.fg, bg = "#2A2B3F" })
-- vim.api.nvim_set_hl(0, "PmenuBorder", { fg = "Black", bg = "#2A2B3F" })
-- vim.api.nvim_set_hl(0, "PmenuThumb", { fg = colors.none, bg = colors.bg_highlight })
--
-- vim.api.nvim_set_hl(0, "CmpItemAbbrDeprecated", { fg = colors.dark3, bg = colors.none })
-- vim.api.nvim_set_hl(0, "CmpItemAbbrMatch", { fg = colors.blue, bg = colors.none, bold = true })
-- vim.api.nvim_set_hl(0, "CmpItemAbbrMatchFuzzy", { fg = colors.blue, bg = colors.none, bold = true })
-- vim.api.nvim_set_hl(0, "CmpItemMenu", { fg = colors.blue, bg = colors.none, italic = true })
--
-- vim.api.nvim_set_hl(0, "CmpItemKindField", { bg = colors.none, fg = colors.red })
-- vim.api.nvim_set_hl(0, "CmpItemKindProperty", { bg = colors.none, fg = colors.red })
-- vim.api.nvim_set_hl(0, "CmpItemKindEvent", { bg = colors.none, fg = colors.red })
--
-- vim.api.nvim_set_hl(0, "CmpItemKindText", { bg = colors.none, fg = colors.green })
-- vim.api.nvim_set_hl(0, "CmpItemKindEnum", { bg = colors.none, fg = colors.green })
-- vim.api.nvim_set_hl(0, "CmpItemKindKeyword", { bg = colors.none, fg = colors.green })
--
-- vim.api.nvim_set_hl(0, "CmpItemKindConstant", { bg = colors.none, fg = colors.orange })
-- vim.api.nvim_set_hl(0, "CmpItemKindConstructor", { bg = colors.none, fg = colors.orange })
-- vim.api.nvim_set_hl(0, "CmpItemKindReference", { bg = colors.none, fg = colors.orange })
--
-- vim.api.nvim_set_hl(0, "CmpItemKindFunction", { bg = colors.none, fg = colors.purple })
-- vim.api.nvim_set_hl(0, "CmpItemKindStruct", { bg = colors.none, fg = colors.purple })
-- vim.api.nvim_set_hl(0, "CmpItemKindClass", { bg = colors.none, fg = colors.purple })
-- vim.api.nvim_set_hl(0, "CmpItemKindModule", { bg = colors.none, fg = colors.purple })
-- vim.api.nvim_set_hl(0, "CmpItemKindOperator", { bg = colors.none, fg = colors.purple })
--
-- vim.api.nvim_set_hl(0, "CmpItemKindVariable", { bg = colors.none, fg = colors.dark5 })
-- vim.api.nvim_set_hl(0, "CmpItemKindFile", { bg = colors.none, fg = colors.dark5 })
--
-- vim.api.nvim_set_hl(0, "CmpItemKindUnit", { bg = colors.none, fg = colors.yellow })
-- vim.api.nvim_set_hl(0, "CmpItemKindSnippet", { bg = colors.none, fg = colors.yellow })
-- vim.api.nvim_set_hl(0, "CmpItemKindFolder", { bg = colors.none, fg = colors.yellow })
--
-- vim.api.nvim_set_hl(0, "CmpItemKindMethod", { bg = colors.none, fg = colors.blue })
-- vim.api.nvim_set_hl(0, "CmpItemKindValue", { bg = colors.none, fg = colors.blue })
-- vim.api.nvim_set_hl(0, "CmpItemKindEnumMember", { bg = colors.none, fg = colors.blue })
--
-- vim.api.nvim_set_hl(0, "CmpItemKindInterface", { bg = colors.none, fg = colors.teal })
-- vim.api.nvim_set_hl(0, "CmpItemKindColor", { bg = colors.none, fg = colors.teal })
-- vim.api.nvim_set_hl(0, "CmpItemKindTypeParameter", { bg = colors.none, fg = colors.teal })
